# Tugas 3 Data Mining

In [21]:
import pandas as pd
import numpy as np

In [22]:
data= pd.read_csv("autoMPG.csv",sep=";")
print(data.shape)
data.head()

(398, 9)


mpg  cylinders  displacement  horsepower  weight  acceleration  model year  \
0   18          8           307       130.0    3504            12          70   
1   15          8           350       165.0    3693            12          70   
2   18          8           318       150.0    3436            11          70   
3   16          8           304       150.0    3433            12          70   
4   17          8           302       140.0    3449            11          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [23]:
dataregresi=data.drop(['cylinders','acceleration','model year','origin','car name'],1)
print(dataregresi.shape)
dataregresi.head()

(398, 4)


mpg  displacement  horsepower  weight
0   18           307       130.0    3504
1   15           350       165.0    3693
2   18           318       150.0    3436
3   16           304       150.0    3433
4   17           302       140.0    3449

In [24]:
dataregresi.describe()

mpg  displacement  horsepower       weight
count  398.000000    398.000000  392.000000   398.000000
mean    23.562814    193.427136  104.469388  2970.424623
std      7.812979    104.268683   38.491160   846.841774
min      9.000000     68.000000   46.000000  1613.000000
25%     18.000000    104.250000   75.000000  2223.750000
50%     23.000000    148.500000   93.500000  2803.500000
75%     29.000000    262.000000  126.000000  3608.000000
max     47.000000    455.000000  230.000000  5140.000000

In [25]:
#Pengecekan missing value
np.sum(dataregresi.isnull())

mpg             0
displacement    0
horsepower      6
weight          0
dtype: int64

## Mengatasi Missing Value

In [26]:
#melakukan imputasi dengan menggunakan nilai mean
dataregresi['horsepower']=dataregresi['horsepower'].fillna (dataregresi['horsepower'].mean())

np.sum(dataregresi.isnull())

mpg             0
displacement    0
horsepower      0
weight          0
dtype: int64

## Model Regresi 1

In [27]:
from random import random
from pandas import DataFrame
from statsmodels.api import OLS
prediktor=['displacement','horsepower','weight']
x = dataregresi[prediktor]
x['b']=1
y = dataregresi.mpg

print (x.head())
print (y.head())

model = OLS(y, x)
result = model.fit()
print(result.summary())

   displacement  horsepower  weight  b
0           307       130.0    3504  1
1           350       165.0    3693  1
2           318       150.0    3436  1
3           304       150.0    3433  1
4           302       140.0    3449  1
0    18
1    15
2    18
3    16
4    17
Name: mpg, dtype: int64
                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.703
Model:                            OLS   Adj. R-squared:                  0.701
Method:                 Least Squares   F-statistic:                     311.0
Date:                Sun, 10 Mar 2019   Prob (F-statistic):          1.68e-103
Time:                        18:48:30   Log-Likelihood:                -1140.8
No. Observations:                 398   AIC:                             2290.
Df Residuals:                     394   BIC:                             2305.
Df Model:                           3                                 

## Mengatasi Missing Value dan Outlier

In [28]:
data= pd.read_csv("autoMPG.csv",sep=";")
dataregresi=data.drop(['cylinders','acceleration','model year','origin','car name'],1)

#Mengatasi Missing value
dataregresi['horsepower']=dataregresi['horsepower'].fillna (dataregresi['horsepower'].mean())
np.sum(dataregresi.isnull())

mpg             0
displacement    0
horsepower      0
weight          0
dtype: int64

In [29]:
#Mengatasi outlier
from scipy import stats
z = np.abs(stats.zscore(dataregresi._get_numeric_data()))
print(z)

dataregresi=dataregresi[(z<3).all(axis=1)]
print(dataregresi.shape)


[[0.71289269 1.09060372 0.66919608 0.63086987]
 [1.09735243 1.5035189  1.58659918 0.85433297]
 [0.71289269 1.19623319 1.19342642 0.55047045]
 ...
 [1.08125277 0.56105701 0.53653371 0.79858454]
 [0.56863978 0.70509719 0.66759129 0.40841088]
 [0.95309953 0.71469987 0.58895674 0.29608816]]
(392, 4)


## Model Regresi 2

In [30]:
from random import random
from pandas import DataFrame
from statsmodels.api import OLS
prediktor=['displacement','horsepower','weight']
x = dataregresi[prediktor]
x['b']=1
y = dataregresi.mpg

print (x.head())
print (y.head())

model = OLS(y, x)
result = model.fit()
print(result.summary())

   displacement  horsepower  weight  b
0           307       130.0    3504  1
1           350       165.0    3693  1
2           318       150.0    3436  1
3           304       150.0    3433  1
4           302       140.0    3449  1
0    18
1    15
2    18
3    16
4    17
Name: mpg, dtype: int64
                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.707
Model:                            OLS   Adj. R-squared:                  0.705
Method:                 Least Squares   F-statistic:                     312.0
Date:                Sun, 10 Mar 2019   Prob (F-statistic):          5.20e-103
Time:                        18:48:42   Log-Likelihood:                -1115.6
No. Observations:                 392   AIC:                             2239.
Df Residuals:                     388   BIC:                             2255.
Df Model:                           3                                 

## Mengatasi Missing Value dan Transformasi

In [38]:
data= pd.read_csv("autoMPG.csv",sep=";")
dataregresi=data.drop(['cylinders','acceleration','model year','origin','car name'],1)

#Mengatasi Missing value
dataregresi['horsepower']=dataregresi['horsepower'].fillna (dataregresi['horsepower'].mean())
np.sum(dataregresi.isnull())

mpg             0
displacement    0
horsepower      0
weight          0
dtype: int64

In [39]:
#Melakukan transformasi dengan menggunakan metode normalization
from sklearn.preprocessing import normalize
regnorm=normalize(dataregresi,norm='l2')
regnorm=pd.DataFrame(regnorm)
print(regnorm.shape)
regnorm.head()

(398, 4)


0         1         2         3
0  0.005114  0.087219  0.036933  0.995491
1  0.004040  0.094257  0.044436  0.994548
2  0.005211  0.092067  0.043428  0.994792
3  0.004638  0.088123  0.043482  0.995149
4  0.004906  0.087156  0.040403  0.995363

## Model Regresi 3

In [41]:
from random import random
from pandas import DataFrame
from statsmodels.api import OLS
x=regnorm.iloc[0:398,1:4]
y=regnorm.iloc[0:398,0:1]

print (x.head())
print (y.head())

model = OLS(y, x)
result = model.fit()
print(result.summary())

          1         2         3
0  0.087219  0.036933  0.995491
1  0.094257  0.044436  0.994548
2  0.092067  0.043428  0.994792
3  0.088123  0.043482  0.995149
4  0.087156  0.040403  0.995363
          0
0  0.005114
1  0.004040
2  0.005211
3  0.004638
4  0.004906
                            OLS Regression Results                            
Dep. Variable:                      0   R-squared:                       0.891
Model:                            OLS   Adj. R-squared:                  0.890
Method:                 Least Squares   F-statistic:                     1071.
Date:                Sun, 10 Mar 2019   Prob (F-statistic):          2.68e-189
Time:                        18:55:03   Log-Likelihood:                 1687.7
No. Observations:                 398   AIC:                            -3369.
Df Residuals:                     395   BIC:                            -3357.
Df Model:                           3                                         
Covariance Type:         

## Mengatasi Missing Value, Outlier dan Transformasi

In [52]:
data= pd.read_csv("autoMPG.csv",sep=";")
dataregresi=data.drop(['cylinders','acceleration','model year','origin','car name'],1)

#Mengatasi Missing value
dataregresi['horsepower']=dataregresi['horsepower'].fillna (dataregresi['horsepower'].mean())
np.sum(dataregresi.isnull())

mpg             0
displacement    0
horsepower      0
weight          0
dtype: int64

In [53]:
#Mengatasi outlier
from scipy import stats
z = np.abs(stats.zscore(dataregresi._get_numeric_data()))
print(z)

dataregresi=dataregresi[(z<3).all(axis=1)]
print(dataregresi.shape)

[[0.71289269 1.09060372 0.66919608 0.63086987]
 [1.09735243 1.5035189  1.58659918 0.85433297]
 [0.71289269 1.19623319 1.19342642 0.55047045]
 ...
 [1.08125277 0.56105701 0.53653371 0.79858454]
 [0.56863978 0.70509719 0.66759129 0.40841088]
 [0.95309953 0.71469987 0.58895674 0.29608816]]
(392, 4)


In [54]:
#Melakukan transformasi dengan menggunakan metode normalization
from sklearn.preprocessing import normalize
regnorm=normalize(dataregresi,norm='l2')
regnorm=pd.DataFrame(regnorm)
print(regnorm.shape)
regnorm.head()

(392, 4)


0         1         2         3
0  0.005114  0.087219  0.036933  0.995491
1  0.004040  0.094257  0.044436  0.994548
2  0.005211  0.092067  0.043428  0.994792
3  0.004638  0.088123  0.043482  0.995149
4  0.004906  0.087156  0.040403  0.995363

## Model Regresi 4

In [56]:
from random import random
from pandas import DataFrame
from statsmodels.api import OLS
x=regnorm.iloc[0:393,1:4]
y=regnorm.iloc[0:393,0:1]

print (x.head())
print (y.head())

model = OLS(y, x)
result = model.fit()
print(result.summary())

          1         2         3
0  0.087219  0.036933  0.995491
1  0.094257  0.044436  0.994548
2  0.092067  0.043428  0.994792
3  0.088123  0.043482  0.995149
4  0.087156  0.040403  0.995363
          0
0  0.005114
1  0.004040
2  0.005211
3  0.004638
4  0.004906
                            OLS Regression Results                            
Dep. Variable:                      0   R-squared:                       0.894
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     1096.
Date:                Sun, 10 Mar 2019   Prob (F-statistic):          2.51e-189
Time:                        19:05:05   Log-Likelihood:                 1668.5
No. Observations:                 392   AIC:                            -3331.
Df Residuals:                     389   BIC:                            -3319.
Df Model:                           3                                         
Covariance Type:         